apiVersion: v1
kind: Service
metadata:
  name: photoreviewer
  namespace: jellyfin
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - name: 'webserver'
      port: 8997
      targetPort: 8997
  selector:
    app: photoreviewer
